apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: capstone
  labels:
    name: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      name: spring-petclinic-pod
  strategy:
    type: Recreate
  template:
    metadata:
      name: spring-petclinic-pod
      labels:
        name: spring-petclinic-pod
    spec:
      containers:
        - name:  spring-petclinic-container
          image: jnaidu023/petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: capstone
  labels:
    name: spring-petclinic-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: spring-petclinic-pod
  type: NodePort
